# Enable OLED Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_EXT_POWER=y

# Force display widget initialization
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y

# SSD1306 screen brightness & orientation
CONFIG_SSD1306=y
CONFIG_SSD1306_REVERSE_MODE=n

# Power management (prevent screen from turning off immediately)
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
